class User {
  final int? id;        // Primary key, nullable because it's generated by SQLite
  final String username;
  final String password;

  User({
    this.id,
    required this.username,
    required this.password,
  });

  // 1. Convert a User object into a Map. 
  // SQLite doesn't understand Dart objects; it only speaks Map/List.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'username': username,
      'password': password,
    };
  }

  // 2. Convert a Map from the database back into a User object.
  // This is used when you fetch data from the database.
  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      id: map['id'] as int?,
      username: map['username'] as String,
      password: map['password'] as String,
    );
  }
}